### ISSUE TITLE
folder creation is not as expected

### ISSUE THREAD

**Issue by cvidler** [cavejay/Strippy#1]
Testing using a folder named `./amdlogs/` produces output `./amdlog.sanitised/s/` not just `./amdlogs.sanitised/` as expected.

![strippy-issue](https://cloud.githubusercontent.com/assets/16074154/24438360/a3e8660a-1492-11e7-90df-a0a97c40cf0d.png)

**Comment by cavejay** [comment]
This is weird. 
ty for the issue though

**Comment by cavejay** [comment]
It looks like it's a linux issue, potentially with a weird splitting of the folder.
