### ISSUE TITLE
Oh Hai Y Du U Sanitise Pictures?

### ISSUE THREAD

**Issue by cavejay** [cavejay/Strippy#2]
Plz Fix.

**Comment by cvidler** [comment]
https://gallery.technet.microsoft.com/scriptcenter/PowerShell-Function-to-6429566c

Check returned mime type is textual otherwise skip it. Maybe re-name it unsanitised or something so it's not overlooked).

**Comment by cavejay** [comment]
That's a good solution, ty

**Comment by cavejay** [comment]
I attempted to implement that snippet of code and it seems to struggle with the `.Exist` parameter. I'll make some changes and see if we can get a sensible mime-type out of things. I seem to mostly get something like application/octet-stream which is unusable if that is returned for both .exes and txt files

I'm considering using some combination of magic number and mime-type checking to determine whether or not to sanitise a file
