### ISSUE TITLE
Please Check Environment for required version/features before running

### ISSUE THREAD

**Issue by cavejay** [cavejay/Strippy#21]
This will prevent people getting frustrated when they try to run the script and have problems but only because they're on an unsupported system

**Comment by JoelStuart** [comment]
Which version have been reporting problems? Might try to test out the older ones when I get to it.

Looking to check $PSVersionTable.PSVersion at startup, but dont want to pre-terminate for older versions that are still runnable.

**Comment by cavejay** [comment]
I'll have to do some testing for this. The following have been reported by others during attempted processing: 
- previous versions of Strippy used write-information which was unavailable prior to v5
- Chris attempted to run Strippy on a client site and the logging code broke somewhere.

My plan was to run with various versions and take note of what failed. v5 is a guaranteed working version and that's what the code has been developed in.

While it is currently untested Strippy should also be perfectly cross platform. While it wasn't the case originally I now make sure to use platform agnostic directory cmdlets

**Comment by cvidler** [comment]
I've tested Strippy with the linux Powershell distribution, it worked fine, but that was a very old version of Strippy, may need further testing.

**Comment by cavejay** [comment]
Using the `#Requires -version 5.0` comment convention should apparently prevent this script from running in older versions of powershell

**Comment by cavejay** [comment]
a95458189c0163da012600014119e61bb0126712 finally implements this. Not sure why it took so long.

The main-line release of Strippy is now limited to Powershell 5.0 and higher. (unless you remove the first line of the script...)
