### ISSUE TITLE
Supplemental post execution sanity check

### ISSUE THREAD

**Issue by cvidler** [cavejay/Strippy#33]
Optionally provide a run through of some basic, less specific regex's, to identify where the sanitisation process may have missed lines.  Here false positives are better than false negatives.

e.g.
Simple regex for picking anything that looks like an IP, without any text context.
Simple regex for picking any single word (space delimited) which contains letter AND numbers, but not all letter or all numbers – find server/workstation names.
Simple regex for picking any single word (space delimited) which contains letters optional numbers but delimited by ‘.’ – find any DNS names

**Comment by cavejay** [comment]
I've been thinking of something similar but have imagined it as a separate script that runs across the files afterwards and checking not for any particular regex rules but simply for 'known-bad' strings.
Sometimes (like during the recent DCRUM upgrade I oversaw) the information that needs to be sanitised can change and a deployment specific check would be useful to quickly catch the strings that slip by.

To that end I've marked this issue as a 'not-planned' as I'm not 100% certain it's within the intended scope of Strippy.

**Comment by cavejay** [comment]
Closing this. 

There _may_ be an auxiliary script at some point that performs something similar to what you're suggesting while also using the split processing code from Strippy, but I believe it should be environment specific rather than generic.
