### ISSUE TITLE
Support for unknown length 'lists' of sensitive data

### ISSUE THREAD

**Issue by mzball** [cavejay/Strippy#36]
Currently the only way to capture more than one piece of sensitive information from the same line is to explicitly capture each piece with a new rule. This works well for cases that are known length, say splitting `domain\user` into a domain and user.

Some times however a log line contains a list of servers or URLs that are best captured individually. If the number of items in this list changes between log sets then support for 'lists' of this data becomes valuable.

--- 
## Suggested Solution

Rule alias' that end in 'List' represent lists of sensitive data. Rather than the `[String1]=[String2]` format of other rules, list rules are represented in the conf file with a `[String1]=[String2],[String3]`.

- `[String1]` - Regex Rule
- `[String2]` - Rule Alias
- `[String3]` - List delimiter

---

## Implementation

This will require updating the config parsing code and the merging process.

**Comment by cavejay** [comment]
Important for parsing new Dt logs usefully

**Comment by cavejay** [comment]
Is it possible to implement this by just looking for other regex matches in the same line? Rather than limiting to the first group, accept the remaining matches?

**Comment by cavejay** [comment]
> 
> 
> Is it possible to implement this by just looking for other regex matches in the same line? Rather than limiting to the first group, accept the remaining matches?

Possibly? The easiest solution is just to switch the internal key list from a tuple (quite restrictive) to either  dict or PSObject and extend the key/vals that way. 

Refactoring the key/val storage would mean that internally 'killerflags' wouldn't need to be treated any differently.

possible schema for new key/val storage replacement
```
type=deleteflag|list|basic
regex=[String showing regex]
replacement=[String]
```

**Comment by cavejay** [comment]
this looks to be implemented and functional - nothing like a field test to confirm though.

Implementation details: 
* Internal rule storage was updated as above (consolidated 'delete' rules w/ basic and new list keys) line [line-ref: outlining schema](https://github.com/cavejay/Strippy/blob/42d08743a329b6180e03d7e5977b712ea7a75e5b/strippy.ps1#L379) [line-ref: proc'ing config](https://github.com/cavejay/Strippy/blob/42d08743a329b6180e03d7e5977b712ea7a75e5b/strippy.ps1#L641)
* During the scouting and Sanitisation stages the delete rules are pulled out and applied in a similar way to how the internal 'killerflags' were. [line-ref: removing lines during scouting](https://github.com/cavejay/Strippy/blob/42d08743a329b6180e03d7e5977b712ea7a75e5b/strippy.ps1#L931) [line-ref: removing lines prior to passing content to sanitisation](https://github.com/cavejay/Strippy/blob/42d08743a329b6180e03d7e5977b712ea7a75e5b/strippy.ps1#L1268)
  * While the above works to close off this issue, code should be revisited to better refactor the killerflags references. At the moment we're effectively just pollyfilling the old code.
* If a token is a list it is split before we check if the keys we've found are already known. I'm quite happy with this implementation. [line-ref](https://github.com/cavejay/Strippy/blob/42d08743a329b6180e03d7e5977b712ea7a75e5b/strippy.ps1#L954)
* Multiline was implemented on the sly - Past cavejay may know more about why that was sitting there commented out - possible the '...' captured with keys that ended a line, but that was resolved with a cleaning of nl characters from all keys. [line-ref: multiline](https://github.com/cavejay/Strippy/blob/42d08743a329b6180e03d7e5977b712ea7a75e5b/strippy.ps1#L947) [line-ref: nl cleaning](https://github.com/cavejay/Strippy/blob/42d08743a329b6180e03d7e5977b712ea7a75e5b/strippy.ps1#L966)
  * Previously ^ and $ would only match on the beginning and end of the entire file, so this is pretty important for useful log parsing.

---

Additional explanation is being provided for those that may be interested in the process of this very large script... That could be no one but future me though.

**Comment by cavejay** [comment]
Closing - official release will be in v2.4.0
