### ISSUE TITLE
Don't modify the format of sanitised files

### ISSUE THREAD

**Issue by cvidler** [cavejay/Strippy#39]
strippy breaks json file parsing by adding the sanitised header.
e.g.

```
This file was Sanitised at 20/03/2019 12:48:48 PM.
==

{"columnHeader":["
```

It also adds an additional CR/LF to the last line.

Surely the change to the file name is sufficient notice the file has been sanitised.

**Comment by cavejay** [comment]
I'll add a switch and update the config setting for this. The first line message is controlled by the "SanitisedFileFirstLine" var in the .conf file. 

While the .sanitised extension does communicate that the file was sanitised it doesn't communicate when and I think that level of meta data is meaningful.
